name: quanta-challenge

services:
  challenge-web-app:
    build:
      context: ../
      dockerfile: packages/challenge-web-app/Dockerfile
    networks:
      - quanta-challenge-network
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://quanta:quanta@postgres:5432/quanta_db
      - NUXT_REDIS_HOST=redis
      - NUXT_APP_BASE_SERVER=https://localhost:3000
      - NUXT_JUDGE_SERVER_URL=http://challenge-judge-scheduler:1888
      - SUPER_ACCOUNT=stillsoda
      - SUPER_PASSWORD=stillsoda123
      - SUPER_EMAIL=stillsoda123@admin.com
    depends_on:
      - challenge-judge-scheduler
      - redis
      - postgres
    volumes:
      - qtc_app_storage:/app/packages/web/local_store # Persist local storage

  challenge-judge-scheduler:
    build:
      context: ../
      dockerfile: packages/challenge-judge-scheduler/Dockerfile
    environment:
      - DATABASE_URL=postgres://quanta:quanta@postgres:5432/quanta_db
      - REDIS_HOST=redis
    depends_on:
      - redis
      - postgres
    networks:
      - quanta-challenge-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Docker outside of Docker

  challenge-judge-machine-agent:
    build:
      context: ../
      dockerfile: packages/challenge-agents/judge-machine/Dockerfile
    profiles:
      - ignore
    extra_hosts:
      - "host.docker.internal:host-gateway"

  challenge-live-server-agent:
    build:
      context: ../
      dockerfile: packages/challenge-agents/live-server/Dockerfile
    profiles:
      - ignore

  redis:
    image: "redis:7-alpine"
    ports:
      - "26379:6379"
    networks:
      - quanta-challenge-network

  postgres:
    image: "postgres:16-alpine"
    environment:
      - POSTGRES_USER=quanta
      - POSTGRES_PASSWORD=quanta
      - POSTGRES_DB=quanta_db
    ports:
      - "25432:5432"
    networks:
      - quanta-challenge-network
    volumes:
      - qtc_postgres_data:/var/lib/postgresql/data

networks:
  quanta-challenge-network:
    driver: bridge

volumes:
  qtc_postgres_data:
  qtc_app_storage:
